### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by zlyfire** [cyanobacterium/SteamAdvantage#12]
I installed this mod via curse onto my game and it's giving me a crash. The crash log seems to indicate that you're attempting to register something to the ore dictionary incorrectly. It's possible it was a change in Forge itself. Here's my crashlog: [Pastebin](http://pastebin.com/xkDT8C5b)  
I have many other mods installed as well, including Power Advantage and Base Metals.  
And yes, this is on MC 1.9 with Forge 12.16.1.1887 (Recommended, and most recent).

**Comment by jriwanek** [comment]
Bug in inventory tweaks:

Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
    at invtweaks.InvTweaksItemTree.lambda$oreRegistered$5(InvTweaksItemTree.java:288)
    at invtweaks.InvTweaksItemTree$$Lambda$164/1735053521.test(Unknown Source)

as it says in your crash report.

**Comment by zlyfire** [comment]
But it didn't start happening until after I had installed Power, Steam, and Electric Advantage. Removing those fixed the problem. And before I had added them it was working fine.

**Comment by DrPlantabyte** [comment]
The stacktrace in your crash report suggests that the problem lies in the code that Inventory Tweaks injected into the Ore Dictionary.

That is an inventory Tweaks bug, but one that only occurs when Power Advantage uses the Ore Dictionary. I don't know enough about Inventory Tweaks to determine why or what the fix is, but my guess is that there's some mod-specific code that didn't get updated.
