### ISSUE TITLE
Steam Powered Drill

### ISSUE THREAD

**Issue by hero887** [cyanobacterium/SteamAdvantage#4]
I wasn't sure without testing, but like other miners does the steam powered drill replace the blocks mined automatically with cobble or dirt or something like that?

Also, does the device have to be chunk loaded at all times to work?

Lastly, will it lag servers? If yes, what advice can you give server owners running this mod to reduce lag spikes?

**Comment by DrPlantabyte** [comment]
The steam-powered drill (and laser drill) do not replace the mined blocks with anything, making them useful for creating tunnels (they can drill sideways). If you place a steam track block (or electric scaffold for the laser drill) next to the drill then the hole will be safely covered with a steel frame block when the drill moves.

The chunk with the drill needs to be loaded for it to work, I'm not sure if the drill will load neighboring chunks if it is turned sideways (I never tested that).

As for server lag, none of my friends have noticed any lag due to the drills. In general, Power Advantage was designed to avoid taxing the server any more than necessary, but of course whether or not you will experience lag depends mostly on hardware factors, especially internet bandwidth, TCP packet loss frequency, and latency.

**Comment by hero887** [comment]
Fantastic! I like the steel frame block idea. Very nice. Thanks man!
